# NOT recommended - just use a fresh image

- name: SCRIPT - Update Bootloader
  ansible.builtin.shell: # pipefail-setting prevents surprises
    cmd: "set -o pipefail && yes | /opt/scripts/tools/developers/update_bootloader.sh"
  changed_when: true
  when: maintenance_update_bootloader | bool
  failed_when: false # certificate may be invalid