---

- name: Test if Node has Access to Internet (essential)
  ansible.builtin.wait_for:
    host: github.com
    port: 80
    state: started
    timeout: 5

- name: Update SSL-Certificates
  ansible.builtin.command: 'update-ca-certificates -f -v'
  changed_when: true

- name: Check if boot-scripts-Repo exists
  ansible.builtin.stat:
    path: /opt/scripts
  register: scripts_dir
- name: GIT - Clone & Update boot-script-tools from RobertCNelson
  ansible.builtin.git:
    repo: https://github.com/RobertCNelson/boot-scripts
    dest: /opt/scripts
    update: true
    version: HEAD  # noqa latest[git]
    force: true
  when: not scripts_dir.stat.exists
- name: Remove space-waster of boot-script-repo (free 13 of 27 mb)
  ansible.builtin.file:
    path:
      [
        "/opt/scripts/.git/",
        "/opt/scripts/device/",
        "/opt/scripts/images/",
      ]
    state: absent

- name: APT - Update Cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: "SCRIPT - Switch to newest release of Kernel Branch {{ maintenance_default_kernel }}"
  ansible.builtin.command: '/opt/scripts/tools/update_kernel.sh --{{ maintenance_default_kernel }}'
  when: maintenance_update_kernel | bool
  changed_when: true
  failed_when: false # allow to fail

- name: Grow root partition to drive-size
  ansible.builtin.command: '/opt/scripts/tools/grow_partition.sh'
  changed_when: true

- name: Restart device
  ansible.builtin.reboot:
    connect_timeout: 20
    reboot_timeout: 200
    post_reboot_delay: 30
  when: maintenance_update_kernel | bool

- name: Uname - Get Kernel-Release
  ansible.builtin.command: 'uname --kernel-release'
  register: kernelrelease
  changed_when: false

- name: APT - Install matching Kernel-Headers for running Kernel
  ansible.builtin.apt:
    name: 'linux-headers-{{ kernelrelease.stdout.strip() }}'

- name: APT - Upgrade all packages to the latest version
  ansible.builtin.apt:
    upgrade: full # was "dist" but this changed also the kernel back to 5.10

- name: "CFG - Set timezone to {{ maintenance_timezone }}"
  community.general.timezone:
    name: "{{ maintenance_timezone }}"

  # TODO: - name: CFG - Set CPU Governor to more relaxed state (powersave)

- name: Include performance-modifications
  ansible.builtin.include_tasks:
    file: performance.yml

- name: Restart device
  ansible.builtin.reboot:
    connect_timeout: 20
    reboot_timeout: 200
    post_reboot_delay: 30
