---

- name: Test if Node has Access to Internet (essential)
  ansible.builtin.wait_for:
    host: github.com
    port: 80
    state: started
    timeout: 5

- name: Update SSL-Certificates
  ansible.builtin.command: 'update-ca-certificates -f -v'
  changed_when: true

- name: APT - Update Cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: APT - Upgrade all packages to the latest version
  ansible.builtin.apt:
    upgrade: dist

- name: "CFG - Set timezone to {{ maintenance_timezone }}"
  community.general.timezone:
    name: "{{ maintenance_timezone }}"

- name: Add ll-alias
  ansible.builtin.lineinfile:
    dest: '{{ item }}/.bashrc'
    line: "alias ll='ls -l'"
    regex: "#?alias ll='ls -l'.*$"
    insertafter: 'EOF'
    state: present
  loop:
    - '/home/{{ ansible_user }}'
    - '/root'

  # TODO: - name: CFG - Set CPU Governor to more relaxed state (powersave)

- name: Include performance-modifications
  ansible.builtin.include_tasks:
    file: performance.yml

- name: Restart device
  ansible.builtin.reboot:
    connect_timeout: 20
    reboot_timeout: 200
    post_reboot_delay: 30
