[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pyright]
root = "./"
include = ['./shepherd', ]
pythonVersion = "3.10"
pythonPlatform = "Linux"
reportMissingParameterType = true
