[project]
name = "shepherd_sheep"
description = "Synchronized Energy Harvesting Emulator and Recorder"
keywords = ["testbed", "beaglebone", "pru", "batteryless", "energyharvesting", "solar"]

authors = [
    {name = "Kai Geissdoerfer", email = "kai.geissdoerfer@tu-dresden.de"},
    {name = "Ingmar Splitt", email = "ingmar.splitt@tu-dresden.de"},
]
maintainers = [{name = "Ingmar Splitt", email = "ingmar.splitt@tu-dresden.de"}]

version = "2026.04.1"

license = "MIT"

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: POSIX :: Linux",
    "Natural Language :: English",
]

requires-python = ">= 3.11"
dependencies = [
    "shepherd-core[elf,inventory]>=2026.04.1",  # limit due to newest features
    "click",
    "numpy",
    "python-periphery<2.0.0", # v2 has no persistence anymore
    "zerorpc",
    "invoke",
    "h5py",
    "psutil",
    "pyserial",
    "ryaml",
    "msgpack",
    "msgpack-numpy",
    "gevent",
    "chromalog",
    "pydantic>2.11.0",  # this release gives a speedbump
    "greenlet",  # added here to allow sourcing from custom uv-index
    "zstandard",  # added here to allow sourcing from custom uv-index
    "pyzmq",  # added here to allow sourcing from custom uv-index
    "setuptools",  # uv complains sometimes, that it is not there
]

[project.optional-dependencies]
dev = []
test = [
    "pytest>7.4.0",  # not compatible with prior versions
    "pyfakefs>5.0.0",  # not compatible with prior versions
    "pytest-timeout",
    "pytest-click",
    "coverage",
#    "flaky",  # TODO: precaution - suspicious instability when installed
]
doc = ["dbus-python"]
all = ["shepherd-sheep[dev,test,doc]"]
# TODO doc should trigger on
# We are installing the DBUS module to build the docs, but the C libraries
# required to build dbus aren't available on RTD, so we need to exclude it
# from the installed dependencies here, and mock it for import in docs/conf.py
# using the autodoc_mock_imports parameter:
# if not os.getenv("READTHEDOCS"):
# requirements.append("dbus-python")

[project.urls]
Homepage = "https://nes-lab.github.io/shepherd-nova"
Documentation = "https://nes-lab.github.io/shepherd"
Issues = "https://github.com/nes-lab/shepherd/issues"
Source = "https://github.com/nes-lab/shepherd"

[project.scripts]
shepherd = "shepherd_sheep.cli:cli" # short form
shepherd-sheep = "shepherd_sheep.cli:cli"
shepherd-launcher = "shepherd_launcher:main"
shepherd-watchdog = "shepherd_watchdog:main"

[build-system]
requires = ["uv_build>=0.11.0,<0.12.0"]
build-backend = "uv_build"
# ⤷ switched to uv because package is not public

[tool.uv.build-backend]
module-root = "./"
module-name = ["shepherd_sheep", "shepherd_launcher", "shepherd_watchdog"]
platforms = ["unix", "linux"]

[tool.aliases]
test = "pytest"

[tool.pytest.ini_options]
markers = [
    "hardware: test requires specific hardware, i.e. needs to run on BBone.",
    "mock_hardware: test on simulated hardware (gets activated automatically when not on BBone)",
    "emulator: shepher-cape must at least have an emulator-cicuit",
    "harvester: shepher-cape must at least have an harvester-cicuit",
    "eeprom_write: test requires writing of EEPROM (add opt --eeprom-write)",
    "src_name: name of virtual source settings (yaml-file or config-entry)",
    "timeout: limit for individual test to finish",
]
# opts: summary for all except passed, verbose result for each tests
addopts = "-vvv --stepwise"
# continue after fail: sudo pytest-3 --stepwise

[tool.coverage.run]
source = ["shepherd_sheep"]

[tool.pyright]
root = "./"
include = ['./shepherd', ]
pythonVersion = "3.10"
pythonPlatform = "Linux"
reportMissingParameterType = true

[tool.uv]
concurrent-downloads = 1
concurrent-builds = 1
concurrent-installs  = 1
# config-settings = { UV_REQUEST_TIMEOUT = 180, UV_TOOL_BIN_DIR = "/usr/local/bin/"}
# no-build-package = ["numpy", "h5py", "zstandard", "gevent", "pyzmq", "greenlet", "msgpack"]
# export UV_TOOL_BIN_DIR=/usr/local/bin/

[[tool.uv.index]]
name = "piwheels"
url = "https://www.piwheels.org/simple"  # TODO: 3.13 supported! switch to py build by astral?
explicit = true
# default = true

[tool.uv.sources]
numpy = { index = "piwheels", marker = "platform_machine == 'armv7l'"}       # 110 min compile
h5py = { index = "piwheels", marker = "platform_machine == 'armv7l'"}        # 54 min
zstandard = { index = "piwheels", marker = "platform_machine == 'armv7l'"}   # 21 min
gevent = { index = "piwheels", marker = "platform_machine == 'armv7l'"}      # 35 min
pyzmq = { index = "piwheels", marker = "platform_machine == 'armv7l'"}       # 25 min
greenlet = { index = "piwheels", marker = "platform_machine == 'armv7l'"}
msgpack = { index = "piwheels", marker = "platform_machine == 'armv7l'"}     # 2 min
ryaml = { index = "piwheels", marker = "platform_machine == 'armv7l'"}   # 25 min

rapidyaml = { index = "piwheels", marker = "platform_machine == 'armv7l'"}   # does not finish, not used ATM
rtoml = { index = "piwheels", marker = "platform_machine == 'armv7l'"} # not used ATM
