# install     pip3 install pre-commit
#             sudo apt install cppcheck
# run         pre-commit run -a
# update deps pre-commit autoupdate
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: detect-private-key
      - id: mixed-line-ending
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: fix-byte-order-marker

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        args: ["--disable", "MD013"] # ignore line length

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.15
    hooks:
      - id: validate-pyproject
        # files: "./software/python-package/pyproject.toml"

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-use-type-annotations
      - id: python-no-log-warn
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
      - id: text-unicode-replacement-char

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.1.7'
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
        # manual run: ruff check . --preview

# TODO: disable, until bug is resolved, maybe connected to
# https://github.com/ansible/ansible-lint/issues/3636
#  - repo: https://github.com/ansible-community/ansible-lint.git
#    rev: v6.20.3
#    hooks:
#      - id: ansible-lint

#  - repo: https://github.com/rstcheck/rstcheck
#    rev: v6.1.2
#    hooks:
#      - id: rstcheck
#        additional_dependencies: [ "rstcheck[sphinx,toml]" ]
#        args: [ "--report-level=WARNING" ]  # otherwise there is too much chatter

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        additional_dependencies: ["tomli"]  # for py<3.11
        exclude: \.(sch|brd|lbr)$

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.6
    hooks:
      - id: clang-format
        types_or: [c++, c]

  # cpp-check comes last! fails if uninstalled
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: cppcheck
        args:
          - "--enable=all"
          - "--std=c99"
          - "--platform=unix32"
          - "--verbose"
          - "-q"
          - "--max-ctu-depth=10"
          - "-isoftware/firmware/_cgt233/"
          - "-isoftware/firmware/_pssp57g/"
          - "--suppress=unusedFunction"
          - "--suppress=variableScope"
          - "--suppress=unreadVariable"
          - "--suppress=missingInclude"
          - "--suppress=unmatchedSuppression"

########################## BETA SECTION #############################

#     - id: clang-tidy
#       args: [ "-checks=bugprone-,cert-,performance-,portability-"]
# TODO: add more c-linters, but there are to many false positives

#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.971
#    hooks:
#      - id: mypy
# TODO: activate mypy -> some work to fix type-annotations
# TODO: github.com/PyCQA/pydocstyle
# TODO: github.com/PyCQA/pylint

#  - repo: https://github.com/RobertCraigie/pyright-python
#    rev: v1.1.298
#    hooks:
#    - id: pyright
#      additional_dependencies:
#      - shepherd-herd
#      - shepherd-sheep

#  - repo: https://github.com/charliermarsh/ruff-pre-commit
#    rev: v0.0.257
#    hooks:
#      - id: ruff
#        args: ["--fix", "--exit-non-zero-on-fix"]

# default_language_version:
#    python: python3.10
