# virtual project for a dev-environment, usable via:
# uv venv
# uv pip install .
[project]
name = "shepherd-main"
version = "2026.03.1"
description = "Infrastructure for the Testbed, mainly focused on the Observers "
readme = "README.md"

dependencies = [
    # "shepherd-sheep[dev,test]",
    "shepherd-herd[all]",
    "shepherd-cal[dev]",
    #"shepherd-pru",
    "sync-analysis",
    "shepherd-data[all]",
    "ansible",
]
requires-python = ">=3.10"

[project.optional-dependencies]
dev = [
    "twine",  # TODO: could be done with uv
    "prek",  # pre-commit plugin-replacement
    "bump2version",
    "ty",
    "pyright",
    "mypy",
    # temporary
    "dearpygui",
]

doc = [
   "sphinx",
   "sphinx-click",
   "sphinx-rtd-theme",
   "sphinx-sitemap",
   "sphinx-design",
   "sphinx-copybutton",
   "sphinxcontrib-typer",
   "autodoc_pydantic",
   #"sphinx-autodoc2",  # TODO: https://myst-parser.readthedocs.io/en/latest/intro.html#extending-sphinx
   "myst-parser",
]

all = ["shepherd-main[dev,doc]"]

[tool.uv]
package = false

[tool.uv.sources]
shepherd-sheep = { path = "./software/python-package", editable = true}
shepherd-herd = { path = "./software/shepherd-herd", editable = true}
shepherd-cal = { path = "./software/shepherd-calibration", editable = true}
shepherd-pru = { path = "./software/firmware/pru0-module-py", editable = true}
sync-analysis = { path = "./software/debug_analyze_time_sync", editable = true}

# temporary dev-versions of sub-packets
#shepherd-data = { git = "https://github.com/nes-lab/shepherd-tools/", branch = "dev", subdirectory = "shepherd_data"}
#shepherd-core = { git = "https://github.com/nes-lab/shepherd-tools/", branch = "dev", subdirectory = "shepherd_core"}

[tool.setuptools]
# alibi declaration to avoid auto-discovery
packages = ["shepherd-herd",]
package-dir = {"" = "./software" }

[tool.pyright]
root = "./"
include = [
    './software/python-package',
    './software/shepherd-herd',
    './tests',
]
pythonVersion = "3.10"
pythonPlatform = "All"
reportMissingParameterType = true

[tool.ty.terminal]
output-format = "concise"

[tool.ty.src]
exclude = ["*/tests/**"]

[tool.codespell]
builtin = "clear,rare,informal,usage,code,en-GB_to_en-US"
skip = "hardware/_deprecated/*,hardware/cape_v2.4c/*,*.svg,*/pages_update.yaml,*/nrf52840.h,*/nrf52840_bitfields.h,*/core_cm4.h"
# TODO: sphinx-entry only included temporarily
# TODO: programmer header-files contain external code
ignore-words-list = "dout,jupyter,stdio,astroid,uint,fram,arange,ro,metre,od"
check-filenames = true
check-hidden = true
