[tool.pyright]
root = "./"
include = [
    './software/python-package',
    './software/shepherd-herd',
    './tests',
]
pythonVersion = "3.10"
pythonPlatform = "All"
reportMissingParameterType = true
