[project]
name = "shepherd-pru"
description = "C-Bindings of the pru-code for virtual harvester, converter & power source"
keywords = ["testbed", "beaglebone", "pru", "batteryless", "energyharvesting", "solar"]

authors = [
    {name = "Ingmar Splitt", email = "ingmar.splitt@tu-dresden.de"},
]
maintainers = [
    {name = "Ingmar Splitt", email = "ingmar.splitt@tu-dresden.de"},
]

version = "2026.05.1"

license = "MIT"

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
    "Natural Language :: English",
]
requires-python = ">= 3.10"
dependencies = [
    "shepherd-core>=2026.02.1", # limit due to newest features
    "tqdm",
]

[project.optional-dependencies]
test = [
    "pytest",
]

[project.urls]
Homepage = "https://nes-lab.github.io/shepherd"
Documentation = "https://nes-lab.github.io/shepherd"
Issues = "https://github.com/nes-lab/shepherd/issues"
Source = "https://github.com/nes-lab/shepherd"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[build-system]
requires = ["setuptools>=61.2"]
build-backend = "setuptools.build_meta"
# do not switch to uv yet, as this is currently easier

[tool.setuptools]
package-dir = {"" = "."}
zip-safe = true
include-package-data = true
platforms = ["unix", "linux"]

[tool.setuptools.packages.find]
where = ["."]
namespaces = false

[tool.setuptools.package-data]
"*" = ["*.so"]

[tool.aliases]
test = "pytest"

[tool.pytest.ini_options]
addopts = "-vvv  --stepwise"
