---
- name: Install ptp package
  ansible.builtin.apt:
    update_cache: true
    name: linuxptp
    state: present
  tags: ptp

- name: Deploy systemd overlay files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/"
    # originals are kept in /lib/systemd/system/
    mode: '0644'
  loop:
    - "phc2sys@.service"
    - "ptp4l@.service"
  tags:
    - ptp
    - conf
  # Tests
  # manual: sudo systemctl restart ptp4l@eth0
  # status: sudo journalctl -u ptp4l@eth0 -f