---
- name: Install ptp package
  ansible.builtin.apt:
    update_cache: true
    name: linuxptp
    state: present
  tags: ptp

- name: Deploy systemd overlay files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/"
    # originals are kept in /lib/systemd/system/
    mode: '0644'
  loop:
    - "phc2sys@.service"
    - "ptp4l@.service"
  tags:
    - ptp
    - conf

- name: Disable services -> will be activated again by server/client-role
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    daemon_reload: true
  loop:
    - phc2sys@eth0.service
    - ptp4l@eth0.service
  failed_when: false  # services may not exist
  tags:
    - ptp
    - conf
  # manual: sudo systemctl restart ptp4l@eth0
  # status: sudo journalctl -u ptp4l@eth0 -f