---
- name: APT - Update Cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install ptp package
  ansible.builtin.apt:
    name: linuxptp
    state: present
  tags: ptp

- name: Configure PTP
  ansible.builtin.lineinfile:
    dest: "/etc/linuxptp/ptp4l.conf"
    regexp: "{{ item.regex }}"
    line: "{{ item.replacement }}"
    state: present
  loop:
    - {
      regex: "clock_servo.*$",
      replacement: "clock_servo  pi",
      # NOTE: linreg is faster at start, BUT Pi is more precise here
    }
    - {
      regex: "time_stamping.*$",
      replacement: "time_stamping     hardware",
    }
  tags:
    - ptp
    - conf

- name: Install ntpdate package
  ansible.builtin.apt:
    name: ntpdate
    state: present
  tags: ptp

- name: Deploy systemd overlay files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/"
    # originals are kept in /lib/systemd/system/
    mode: '0644'
  loop:
    - "phc2sys@.service"
    - "ptp4l@.service"
  tags:
    - ptp
    - conf
  # Tests
  # manual: sudo systemctl restart ptp4l@eth0
  # status: sudo journalctl -u ptp4l@eth0 -f

- name: Install ethtool
  ansible.builtin.apt:
    name: ethtool
    state: present
  tags: ptp

- name: Check interface capabilities
  ansible.builtin.shell:
    cmd: "set -o pipefail && ethtool -T eth0 | grep {{ item }}"
  loop:
    - hardware-raw-clock
    - hardware-transmit
    - hardware-receive
  failed_when: false
  tags: ptp
