---
- name: APT - Update Cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install ptp package
  ansible.builtin.apt:
    name: linuxptp
    state: present
  tags: ptp

- name: Compile newest LinuxPTP
  ansible.builtin.include_tasks:
    file: compile_ptp.yml

- name: Configure PTP - Hardware-timestamping
  ansible.builtin.lineinfile:
    dest: "/etc/linuxptp/ptp4l.conf"
    regexp: "{{ item.regex }}"
    line: "{{ item.replacement }}"
    state: present
  loop:
    - {
      regex: "clock_servo.*$",
      replacement: "clock_servo  pi",
      # NOTE: linreg is faster at start, BUT Pi is more precise here
    }
    - {
      regex: "time_stamping.*$",
      replacement: "time_stamping     hardware",
    }
  tags:
    - ptp
    - conf

- name: Configure PTP - relax Timeouts
  ansible.builtin.lineinfile:
    dest: "/etc/linuxptp/ptp4l.conf"
    regexp: "{{ item.regex }}"
    line: "{{ item.replacement }}"
    state: present
  loop:
    - {
      regex: "^.?tx_timestamp_timeout.*$",
      replacement: "tx_timestamp_timeout  10", # 1 is default
    }

- name: Configure PTP - higher Prio
  ansible.builtin.lineinfile:
    dest: "/etc/linuxptp/ptp4l.conf"
    regexp: "{{ item.regex }}"
    line: "{{ item.replacement }}"
    state: present
  loop:
    - {
      regex: "^.?dscp_event.*$",
      replacement: "dscp_event  48", # 0 is default
    }
    - {
      regex: "^.?dscp_general.*$",
      replacement: "dscp_general  48", # 0 is default
      # https://en.wikipedia.org/wiki/Differentiated_services#Class_Selector
      # should be higher than 32 (rt communication)
    }
    - {
      regex: "^.?socket_priority.*$",
      replacement: "socket_priority 7", # 0 is default
      # newer versions (v4?, NOT v3.1.1) allow to set SO_PRIORITY also for non '-2'-option
    }

- name: Configure PTP - faster Fault-recovery & better Protection
  ansible.builtin.lineinfile:
    dest: "/etc/linuxptp/ptp4l.conf"
    regexp: "{{ item.regex }}"
    line: "{{ item.replacement }}"
    state: present
  loop:
    - {
      regex: "^.?fault_reset_interval.*$",
      replacement: "fault_reset_interval  0", # 4 is default
      # 4 => 16 s recovery (2^n), -128 and ASAP are possible values
      # TODO: start with 0, try -128
    }
    - {
      regex: "^.?fault_badpeernet_interval.*$",
      replacement: "fault_badpeernet_interval  0", # 4 is default
      # 4 => 16 s recovery (2^n), -128 and ASAP are possible values
    }
    - {
      regex: "^.?check_fup_sync.*$",
      replacement: "check_fup_sync  1", # 0 is default
      # protection against package reordering in network
    }
    - {
      regex: "^.?announceReceiptTimeout.*$",
      replacement: "announceReceiptTimeout  3", # 3 is default
      # allowed missed messages
    }
    - {
      regex: "^.?syncReceiptTimeout.*$",
      replacement: "syncReceiptTimeout  3", # 0 is default
      # allowed missed messages, now same as announceReceiptTimeout
    }
    - {
      regex: "^.?hwts_filter.*$",
      replacement: "hwts_filter  normal", # normal is default
      # - None, when line not present
      # - Normal mode set the filters as needed.
      # - Check mode only check but do not set.
      # - Full mode set the receive filter to mark all packets with hardware time stamp,
      #   so all applications can get them.
      #
      # - note1: full does not work  (ptp v3.1.1, kernel 4.19)
      #         Error "ioctl SIOCSHWTSTAMP failed: Numerical result out of range"
      # - note2: check does not work (ptp v3.1.1, kernel 4.19)
      #         Error "The current filter does not match the required"
    }

- name: Install ntpdate package
  ansible.builtin.apt:
    name: ntpdate
    state: present
  tags: ptp

- name: Deploy systemd overlay files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/"
    # originals are kept in /lib/systemd/system/
    mode: '0644'
  loop:
    - "phc2sys@.service"
    - "ptp4l@.service"
  tags:
    - ptp
    - conf
  # Tests
  # manual: sudo systemctl restart ptp4l@eth0
  # status: sudo journalctl -u ptp4l@eth0 -f

- name: Deploy prio-script for kworker
  ansible.builtin.copy:
    src: "set-ptp-kworker-prio.sh"
    dest: "/usr/local/bin/"
    mode: '0755'
  tags:
    - ptp
    - conf

- name: allow more RT-threads
  ansible.builtin.lineinfile:
    dest: "/etc/sysctl.d/99-rt.conf"
    regexp: "^.?kernel.sched_rt_runtime_us.*$"
    line: "kernel.sched_rt_runtime_us = -1"
    state: present
    create: true

- name: allow more RT-threads (immediate)
  ansible.builtin.shell:
    cmd: sudo sysctl -w kernel.sched_rt_runtime_us=-1

- name: Install ethtool
  ansible.builtin.apt:
    name: ethtool
    state: present
  tags: ptp

- name: Check interface capabilities
  ansible.builtin.shell:
    cmd: "set -o pipefail && ethtool -T eth0 | grep {{ item }}"
  loop:
    - hardware-raw-clock
    - hardware-transmit
    - hardware-receive
  failed_when: false
  tags: ptp

- name: Determine CPU-Governor
  ansible.builtin.command: 'cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor'
  register: cpu_governor
  changed_when: false

- name: Check active CPU-Governor (should be 'performance')
  ansible.builtin.debug:
    msg:
      - "gov={{ cpu_governor.stdout.strip() }}"
