---
# install shepherd-software, all dependencies & roles set in inventory-file

- name: Install Shepherd-Software - Role-based
  hosts: all
  become: true

  pre_tasks:

    - name: Get time and date from ansible controller
      ansible.builtin.command: 'date -u +"%Y-%m-%dT%H:%M:%SZ"'
      delegate_to: localhost
      changed_when: false
      register: local_time
      become: false
    - name: Set correct time
      ansible.builtin.command: "date -s {{ local_time.stdout }}"
      changed_when: true

- name: Role - PTP-Client only
  hosts: ptp_clients
  become: true
  strategy: free # noqa: run-once[play]
  roles:
    - ptp_client

- name: Role - NTP-Client
  hosts: ntp_clients
  become: true
  strategy: free # noqa: run-once[play]
  roles:
    - ntp_client

- name: Role - GPS-Client
  hosts: gps_clients
  become: true
  strategy: free # noqa: run-once[play]
  roles:
    - gps_client
# TODO: how to avoid allowing gps & ptp & ntp client? trouble ahead
#       -> could switch to components and argument_specs
#       https://steampunk.si/blog/ansible-role-argument-specification/

- name: Role - PTP-Server
  hosts: ptp_servers
  become: true
  strategy: free # noqa: run-once[play]
  roles:
    - ptp_server

- name: Role - Secured Testbed
  hosts: secured
  become: true
  strategy: free # noqa: run-once[play]
  roles:
    - secure_testbed
