---
# cleanes up sheep0 to allow pulling an image

- name: Delete space wasting or forgotten files (WARNING - includes recordings) and cleans up free space to prepare image-extraction
  hosts: sheep0
  become: true
  gather_facts: true

  vars:
    cmd_ssh: "ssh {{ ansible_user }}@{{ inventory_hostname }}"
    image_name: "shepherd-ubuntu-22.04.2-console-armhf-{{ ansible_date_time.date }}-4g.img.gz"

  tasks:

    - name: Cleanup Beaglebone
      ansible.builtin.include_role:
        name: cleaning
      vars:
        cleaning_delete_recordings: true
        cleaning_remove_software: false
        cleaning_zero_free_space: true


    - name: Last Step - run the following backup-command manually
      ansible.builtin.debug:
        msg: "{{ cmd_ssh }} 'sudo dd if=/dev/mmcblk1' | xz -6 - | dd of={{ image_name }}"

# TODO: test - do actual command
# hostvars[inventory_hostname]['ansible_default_ipv4']['address']

# base: 1.7 gb used, 1.7 gb free, 51% usage
# ssh jacob@192.168.165.227 'sudo dd if=/dev/mmcblk1' | gzip -1 - | dd of=image.img.gz -> 742 mb 1300s
# ssh jacob@192.168.165.227 'sudo dd if=/dev/mmcblk1' | lzma -3 - | dd of=image.img.xz -> 466 mb 1320s
# ssh jacob@192.168.165.227 'sudo dd if=/dev/mmcblk1' | xz -3 - |  dd of=image3.img.xz -> 466 mb 1333s
# ssh jane@10.0.0.11 'sudo dd if=/dev/mmcblk1' | xz -6 - |  dd of=image.img.xz         -> 384 mb  785s
# ssh jane@sheep0 'sudo dd if=/dev/mmcblk1' | xz -6 - |  dd of=image.img.xz         -> 384 mb  785s
# base: 1.4 gb used, 2.0 gb free, 41 % usage -> 363 mb,
# - remove gcc-8, fw/iw
# base: 1.2 gb used, 2.2 gb free, 36 % usage -> 326 mb,
# base without shp: 788 - 825 mb, 2023-02-25, 1.4 gb with shp

# safe without xz, mount, change uEnv.txt, umount, xz
# sudo mkdir /mnt/image
# sudo mount -o loop /home/NAME/Downloads/image.dd /mnt/image
