---
- name: Refresh Src, compile and install PRU-Fw, restart Kernel-Module, reinstall py-package, without Reboot
  hosts: all
  become: true

  vars_prompt:
    # automatically skip prompt with argument: -e "refresh_from_host=True"
    - name: refresh_from_host
      prompt: "Do you want to distribute the shepherd-source from host to nodes?"
      private: false
      default: "no"

  tasks:

    - name: Rebuild Software
      ansible.builtin.include_role:
        name: sheep
      vars:
        sheep_install_basics: false
        sheep_shepherd_branch: dev  # default: main
        sheep_refresh_source: "{{ refresh_from_host }}"
        sheep_rebuild_kernel_module: true  # default: true
        sheep_rebuild_python_package: true # default: true
