---

- name: Update Time
  hosts: sheep
  become: true
  # strategy: free  # noqa: run-once[play]
  # ⤷ ansible won't wait for every host to continue next task

  tasks:

    - name: Get time and date from ansible controller
      ansible.builtin.command: 'date -u +"%Y-%m-%dT%H:%M:%SZ"'
      delegate_to: localhost
      changed_when: false
      register: local_time
      become: false
    - name: Set correct time
      ansible.builtin.command: "date -s {{ local_time.stdout }}"
      changed_when: true

- name: PTP-Host -> update service-config
  hosts: sheep
  become: true
  strategy: free # noqa: run-once[play]
  roles:
    - ptp_host
    # Tuning is now completely integrated here

- name: Resync
  hosts: sheep
  become: true

  tasks:

    - name: Resync
      ansible.builtin.shell:
        cmd: sudo shepherd-sheep resync
      failed_when: false # may be not connected to timeserver
