---
# will copy keys from nodes, handy firmware resets, while keeping keys

- name: Base setup
  hosts: all

  tasks:

    - name: Prepare directory per host
      ansible.builtin.file:
        path: "{{ playbook_dir }}/keys/{{ inventory_hostname }}/"
        state: directory
        mode: 'a+rx,u+w' # everyone can list and access files inside (+ owner can create & delete)
      delegate_to: localhost

    - name: Fetch keys
      ansible.builtin.fetch:
        src: '/etc/ssh/{{ item }}'
        dest: '{{ playbook_dir }}/keys/{{ inventory_hostname }}/'
        flat: true
      become: true
      loop:
        - ssh_host_ecdsa_key
        - ssh_host_ecdsa_key.pub
        - ssh_host_ed25519_key
        - ssh_host_ed25519_key.pub
        - ssh_host_rsa_key
        - ssh_host_rsa_key.pub
