---
# will handle updates, some configuration, remove clutter, improve ram-usage and boot-duration

- name: Update software & cleanup
  hosts: all
  become: true
  strategy: free # noqa: run-once[play]

  vars_prompt:
    # automatically skip prompt with argument: -e "delete_recordings=True"
    - name: delete_recordings
      prompt: "Do you want to cleanout /var/shepherd/recordings/ on nodes?"
      private: false
      default: "no"

  tasks:

    - name: Maintain Beaglebone
      ansible.builtin.include_role:
        name: maintenance
      vars:
        maintenance_update_kernel: true
        maintenance_update_bootloader: true
        maintenance_delete_unused_files: false  # see below

    - name: Cleanup Beaglebone
      ansible.builtin.include_role:
        name: cleaning
      vars:
        cleaning_delete_recordings: "{{ delete_recordings }}"
        cleaning_remove_software: true
        cleaning_zero_free_space: false
