---
# proposed by helpdesk - login-server and dgw share home-directory
# - get network storage with nfs share
# - enable access for server AND testbed-network

# Storage-benchmarks from BBB:
# sudo dd if=/dev/zero of=./testfile bs=100M count=10 oflag=direct
#     nfsver=4 -> 1000 mb in 91 s, 11.5 MB/s
# sudo dd if=/dev/zero of=./testfile bs=100M count=10
#     nfsver=4 -> 1000 mb in 91 s, 11.5 MB/s

# Storage-benchmarks from vServer:
# sudo dd if=/dev/zero of=./testfile bs=400M count=20 oflag=direct
#     nfsver=4 -> 8.4 GB in 34 s, 250 MB/s

- name: Add (network) datastorage to remote nodes
  hosts: all
  become: true
  gather_facts: true

  vars:
    nfs_server: cephnfs.zih.tu-dresden.de:/glw/shepherd_b/
    # data will be stored in       {{nfs_server}}/experiments/{{ansible_hostname}}/
    # content will be sourced from {{nfs_server}}/content/
    data_path_local: /var/shepherd/

  pre_tasks:

    - name: Report hostname
      ansible.builtin.debug:
        var: ansible_hostname

    - name: create mount-point
      ansible.builtin.file:
        path: "/tmp/shp_drive/"
        state: directory
        mode: "a+rwx"

    - name: Mount root of datastorage
      ansible.builtin.command:
        cmd: "mount -t nfs4 {{ nfs_server }} /tmp/shp_drive/"

    - name: create directories (future mount-points of nfs-share)
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "a+rwx"
      loop:
        - "/tmp/shp_drive/experiments/"
        - "/tmp/shp_drive/experiments/{{ ansible_hostname }}"
        - "/tmp/shp_drive/content/"

  tasks:

    - name: Create local mount-directory
      ansible.builtin.file:
        path: "{{ item }}/"
        state: directory
        owner: "{{ ansible_user }}"
        mode: 'a+rwx'
      loop:
        - "{{ data_path_local }}/experiments"
        - "{{ data_path_local }}/content"

    - name: Remove previous fstab-mountings
      ansible.builtin.lineinfile:
        dest: /etc/fstab
        regex: '^.*{{ nfs_server }}.*$'
        state: absent

    - name: Allow automatic Mounting (Experiments)
      ansible.builtin.lineinfile:
        dest: /etc/fstab
        regex: '^.*{{ nfs_server }}/experiments.*$'
        line: '{{ nfs_server }}/experiments/{{ ansible_hostname }}/ {{ data_path_local }}/experiments nfs4 rw,user,noexec,posix 0 1'
        state: present

    - name: Allow automatic Mounting (Content, readonly)
      ansible.builtin.lineinfile:
        dest: /etc/fstab
        regex: '^.*{{ nfs_server }}/content.*$'
        line: '{{ nfs_server }}/content/ {{ data_path_local }}/content nfs4 ro,user,noexec,posix 0 1'
        state: present

  post_tasks:

    - name: Restart device
      ansible.builtin.reboot:
        connect_timeout: 20
        reboot_timeout: 200
        post_reboot_delay: 30
