---
### basic config
sheep_install_path: /opt/shepherd
sheep_data_path: /var/shepherd/recordings
sheep_config_path: /etc/shepherd

### program flow
sheep_install_basics: true
sheep_install_gcc_tools: false
sheep_install_ti_tools: true
# NOTE: GCC is alpha-stage as pru0-firmware does not correctly compile

sheep_shepherd_branch: main
sheep_refresh_source: false
sheep_rebuild_kernel_module: true
sheep_rebuild_python_package: true

### KERNEL ######
sheep_kernel_pin: "4.19.94-ti-r74"  # 2024-07-03: r74 was newest
# -rt -> used for more reliable ptp & gpio-triggering, BUT communication with PRU fails

### GCC ######
sheep_gcc_tools_path: /usr/share/shepherd-tools
sheep_gcc_pru_support_path: /usr/share/shepherd-tools/pru-software-support-package
sheep_gcc_pru_cc_link: https://github.com/dinuxbg/gnupru/releases/download/2023.05
sheep_gcc_pru_cc_release: pru-elf-2023.05.arm
# Source: https://github.com/dinuxbg/gnupru  -> TODO: the ending was .armhf before + internal change -> look for that var and fix playbooks
sheep_gcc_pru_support_branch: linux-4.19-rproc
# Source: https://github.com/dinuxbg/pru-software-support-package

### TI CGT ###
sheep_ti_tools_path: /usr/share/ti
sheep_ti_pru_cgt_path: /usr/share/ti/cgt-pru
# cgt seems to install to /usr/bin/
sheep_ti_pru_support_path: /usr/share/ti/pru-software-support-package
sheep_ti_pru_cgt_installer: https://software-dl.ti.com/codegen/esd/cgt_public_sw/PRU/2.3.3/ti_cgt_pru_2.3.3_armlinuxa8hf_busybox_installer.sh
# CGT-Updates: https://www.ti.com/tool/PRU-CGT#downloads
sheep_ti_pru_support_tag: "v5.9.0"
# PSSP-Updates: https://git.ti.com/cgit/pru-software-support-package/pru-software-support-package/
# Note: >= v6.0.0 is reserved for kernel >=5.10 and needs a intc_map.h
