- name: Disable GPS and PTP services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    daemon_reload: true
  loop:
    - chrony.service
    - gpsd.service
    - gpsd.socket
    - phc2sys@eth0.service
    - ptp4l@eth0.service
  failed_when: false  # services may not exist
  tags:
    - ptp
    - conf

- name: Enable NTP service
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted
    enabled: true
    daemon_reload: true
  tags:
    - ptp
    - conf
