[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pyright]
root = "./"
include = ['./shepherd_herd', ]
pythonVersion = "3.10"
pythonPlatform = "All"
reportMissingParameterType = true
