---

- name: Determine old local hostname
  ansible.builtin.shell:
    cmd: "hostname"
  register: old_hostname
  changed_when: false

- name: Determine local MAC-Address
  ansible.builtin.shell: # pipefail-setting prevents surprises
    #cmd: "set -o pipefail && ip link show eth0 | grep link/ether | cut -d ' ' --fields=6"
    cmd: "ip link show eth0 | grep link/ether | cut -d ' ' --fields=6"
  register: mac_ret
  failed_when: false
  changed_when: false

- name: Reformat MAC-Address
  ansible.builtin.set_fact:
    mac_add: "{{ mac_ret.stdout | upper | replace(':', '_') }}"

- name: Show MAC
  ansible.builtin.debug:
    var: mac_add

- name: Lookup new host-name
  ansible.builtin.set_fact:
    testbed_observer_hostname: "{{ testbed_observer_mac_2_ip[mac_add][0] }}"

- name: Show new Name
  ansible.builtin.debug:
    var: testbed_observer_hostname

- name: Set hostname (from MAC)
  ansible.builtin.hostname:
    name: "{{ testbed_observer_hostname }}"
  when: old_hostname.stdout.strip() != testbed_observer_hostname

- name: Integrate NW-Storage
  ansible.builtin.include_tasks:
    file: integrate_nes_datastorage.yml

- name: Enable Broadcast of MAC
  ansible.builtin.include_tasks:
    file: broadcast_mac.yml

- name: Extended watchdog reboots unreachable observers in testbed
  ansible.builtin.include_tasks:
    file: activate_internet_watchdog.yml

- name: UV - Install bson - needed for unpacking pickles from timeaware mongodb-server
  ansible.builtin.command:
    cmd: "sudo -E /usr/local/bin/uv pip install bson --upgrade --system --break-system-packages"

- name: Restart device
  ansible.builtin.reboot:
    connect_timeout: 20
    reboot_timeout: 100
    post_reboot_delay: 30
  failed_when: false
  # these nodes should not come back - as the range is about to change
  # from here:
  # - check new IPs (might change after some minutes runtime)
  # - check if host-name matches - reboot accordingly
  # - and/or rerun bootstrap to rewrite host-names

- name: Determine local hostname
  ansible.builtin.shell:
    cmd: "hostname"
  register: new_hostname
  changed_when: false

- name: Show actual new hostname
  ansible.builtin.debug:
    var: new_hostname
