---

- name: Derive Hostname from MAC
  ansible.builtin.include_tasks:
    file: derive_hostname_from_mac.yml

- name: Integrate NW-Storage
  ansible.builtin.include_tasks:
    file: integrate_nes_datastorage.yml

- name: Enable Broadcast of MAC
  ansible.builtin.include_tasks:
    file: broadcast_mac.yml

- name: Grow Root-Filesystem (for fresh images)
  ansible.builtin.include_tasks:
    file: grow_root_partition.yml

- name: Extended watchdog reboots unreachable observers in testbed
  ansible.builtin.include_tasks:
    file: activate_internet_watchdog.yml

- name: UV - Install bson - needed for unpacking pickles from timeaware mongodb-server
  ansible.builtin.command:
    cmd: "sudo -E /usr/local/bin/uv pip install bson --upgrade --system --break-system-packages"

- name: Restart device
  ansible.builtin.reboot:
    connect_timeout: 20
    reboot_timeout: 100
    post_reboot_delay: 30
  failed_when: false
  # these nodes should not come back - as the range is about to change
  # from here:
  # - check new IPs (might change after some minutes runtime)
  # - check if host-name matches - reboot accordingly
  # - and/or rerun bootstrap to rewrite host-names

- name: Determine local hostname
  ansible.builtin.shell:
    cmd: "hostname"
  register: new_hostname
  changed_when: false

- name: Show actual new hostname
  ansible.builtin.debug:
    msg: "{{ new_hostname.stdout }}"
