[project]
name = "shepherd_cal"
authors = [{name = "Kai Geissdoerfer", email = "kai.geissdoerfer@tu-dresden.de"}, {name = "Ingmar Splitt"}]
maintainers = [{email = "ingmar.splitt@tu-dresden.de"}]

description = "Synchronized Energy Harvesting Emulator and Recorder CLI"
keywords = ["testbed", "beaglebone", "pru", "batteryless", "energyharvesting", "solar"]

version = "2026.06.1"

license = "MIT"

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Natural Language :: English",
]

requires-python = ">= 3.10,< 3.13"
# upper limit due to keithley2600-package using xdrlib
# https://github.com/OE-FET/keithley2600/issues/48

dependencies = [
    "typer",
    "fabric",
    "matplotlib",
    "msgpack",
    "msgpack_numpy",
    "numpy",
    "pandas>=2.0.0",  # not compatible with prior versions
    "scipy",
    "zerorpc",
    # shepherd @ git+https://github.com/nes-lab/shepherd.git#subdirectory=software/python-package/
    "keithley2600",
    "shepherd-core",
]

[project.optional-dependencies]
dev = [
    "pandas-stubs",
]

[project.urls]
Issues = "https://github.com/nes-lab/shepherd/issues"
Source = "https://github.com/nes-lab/shepherd"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.scripts]
shepherd-cal = "shepherd_cal.cli:cli"

[build-system]
requires = ["uv_build>=0.11.0,<0.12.0"]
build-backend = "uv_build"
# ⤷ switched to uv because package is not public

[tool.uv.build-backend]
module-root = "./"
platforms = ["unix", "linux",  "osx", "cygwin", "win32", "win64"]
