---

- name: Uname - Get Kernel-Release
  ansible.builtin.command: 'uname --kernel-release'
  register: kernelrelease
  changed_when: false
- name: Inform about Kernel-Version
  ansible.builtin.debug:
    msg:
      - "active   = {{ kernelrelease.stdout.strip() }}"
      - "required = {{ cleaning_required_kernel_regex }} (regex)"
- name: Check for required Kernel-Version
  ansible.builtin.fail:
    msg: |
      Required Kernel-Version not active!
      -> update_kernel.sh failed or /boot/uEnv.txt got changed
  when: kernelrelease.stdout.strip() is not ansible.builtin.search(cleaning_required_kernel_regex)
  # a wrong version would brick the image with the apt-task below

- name: APT - Uninstall non-essential Packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
    purge: true
  failed_when: false
  with_items: "{{ cleaning_packages }}"
