---

- name: Clean apt-caches - 0 - builtin.apt seems broken
  ansible.builtin.command: 'apt autoclean'
  become: true
- name: Clean apt-caches - A
  ansible.builtin.apt:
    autoremove: true
- name: Clean apt-caches - B
  ansible.builtin.apt:
    autoclean: true
- name: Clean apt-caches - C
  ansible.builtin.apt:
    clean: true
  when: false # ansible states that "clean" parameter does not exist
- name: Clean apt-caches - D - builtin.apt seems broken
  ansible.builtin.command: 'apt autoclean'
  become: true

- name: Clean pip-caches - A
  ansible.builtin.file:
    path: "/root/.cache/pip"
    state: absent
  become: true
- name: Clean pip-caches - B
  ansible.builtin.file:
    path: "~/.cache/pip"
    state: absent
  become: false

- name: Clean Journal-Logs - A - liberate
  ansible.builtin.command: 'journalctl --flush --rotate'
  changed_when: true
- name: Clean Journal-Logs - B - delete
  ansible.builtin.command: 'journalctl --vacuum-time=1s'
  changed_when: true

- name: Find Logs and other tmp-files
  ansible.builtin.find:
    paths: ["/var/log/", "/var/lib/apt/lists"]
    patterns: '*'
    recurse: true
  register: files_tmp
- name: Delete Logs and other tmp-files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ files_tmp.files | map(attribute='path') }}"

- name: Discard unused blocks (trim)
  ansible.builtin.command: 'fstrim -a'
  changed_when: true
