---

- name: Get time and date from ansible controller
  ansible.builtin.command: 'date -u +"%Y-%m-%dT%H:%M:%SZ"'
  delegate_to: localhost
  changed_when: false
  register: local_time
  become: false
- name: Set correct time
  ansible.builtin.command: "date -s {{ local_time.stdout }}"
  changed_when: true
  # -> needed for correct journal-cleaning

- name: Clean apt-caches - A
  ansible.builtin.apt:
    autoremove: true
- name: Clean apt-caches - B
  ansible.builtin.apt:
    autoclean: true
- name: Clean apt-caches - C - builtin.apt seems broken
  ansible.builtin.command: 'apt clean'
  become: true
- name: Clean apt-caches - D - builtin.apt seems broken
  ansible.builtin.command: 'apt autoclean'
  become: true
- name: Clean apt-caches - E - clean cache-dir
  ansible.builtin.command: 'rm -rf /var/cache/apt'
  become: true
- name: Clean apt-caches - F - clean list-dir
  ansible.builtin.command: 'rm -rf /var/lib/apt/lists'
  become: true

- name: Sync
  ansible.builtin.command: 'sync'
  changed_when: true
  become: true

- name: Discard unused blocks (trim)
  ansible.builtin.command: 'fstrim -a'
  changed_when: true
  become: true

- name: Clean Journal-Logs - A - liberate
  ansible.builtin.command: 'journalctl --flush --rotate'
  changed_when: true
  become: true
- name: Clean Journal-Logs - B - delete
  ansible.builtin.command: 'journalctl --vacuum-time=1s'
  # should clean /var/log/journal/
  changed_when: true
  become: true
