---

- name: Restart device
  ansible.builtin.reboot:
    connect_timeout: 20
    reboot_timeout: 200
    post_reboot_delay: 30

- name: Discard unused blocks (trim)
  ansible.builtin.command: 'fstrim -a'
  changed_when: true

- name: Determine free space
  ansible.builtin.command: 'df -m /opt/ --output\=avail'
  register: opt_freespace_mb
  changed_when: false

- name: Overwrite empty space
  community.general.filesize:
    path: "/opt/zero_file"
    blocksize: "8M"
    source: "/dev/zero"
    size: "{{ opt_freespace_mb.stdout_lines[-1] | float - 20 }}MB"

- name: Remove empty space file
  ansible.builtin.file:
    path: '/opt/zero_file'
    state: absent
  register: rm_zero_ret
  until: rm_zero_ret is not failed
  retries: 5

- name: Sync
  ansible.builtin.command: 'sync'
  changed_when: true

- name: Discard unused blocks (trim)
  ansible.builtin.command: 'fstrim -a'
  changed_when: true
