---

galaxy_info:
  description: Install GPS-Synchronization - Linux learns understanding the PPS-Signal
  company: NES-Lab
  author: Ingmar
  license: MIT
  standalone: true
  min_ansible_version: 2.8
  platforms:
    - name: Debian
      versions: all
    - name: Ubuntu
      versions: all
collections:
  - ansible.posix
