---

- name: Refresh list of kernel modules
  ansible.builtin.command: 'depmod -a'
  when: sheep_rebuild_kernel_module | bool
  changed_when: true
  tags:
    - install

- name: Load Shepherd-Module
  ansible.builtin.command: 'modprobe -a shepherd'
  changed_when: true

- name: UV - prune local cache
  ansible.builtin.command:
    cmd: 'sudo -E /usr/local/bin/uv cache prune'
    chdir: '/home/{{ ansible_user }}'
  become: false

- name: UV - prune root cache
  ansible.builtin.command:
    cmd: '/usr/local/bin/uv cache prune'
    chdir: '/root/'
  become: true
