---

- name: Stop Kernel Module
  ansible.builtin.command: 'modprobe -rf shepherd'
  failed_when: '{{ item }}'
  loop:
    - false  # just repeat 3 times
    - false
    - false
  # lsmod | grep shepherd
  #   -> loaded: 2 lines, exit 0
  #   -> notload: 0 lines, exit 1
  # return of lsmod not working as expected

- name: Check if PRU1 is present
  ansible.builtin.stat:
    path: "/sys/class/remoteproc/remoteproc1/state"
  register: sysfs_pru
- name: Stop PRU1
  ansible.builtin.shell:
    cmd: 'echo "stop" > /sys/class/remoteproc/remoteproc1/state'
  when: sysfs_pru.stat.exists
  failed_when: false
  changed_when: true

- name: Check if PRU2 is present
  ansible.builtin.stat:
    path: "/sys/class/remoteproc/remoteproc2/state"
  register: sysfs_pru
- name: Stop PRU2
  ansible.builtin.shell:
    cmd: 'echo "stop" > /sys/class/remoteproc/remoteproc2/state'
  when: sysfs_pru.stat.exists
  failed_when: false
  changed_when: true

- name: UV - Uninstall shepherd python package
  ansible:builtin:command:
    cmd: "uv pip uninstall {{ item }}"
  loop:
    - shepherd-core
    - shepherd_core
    - shepherd-sheep
    - shepherd_sheep
  tags:
    - install
    - python
  when: sheep_rebuild_python_package | bool
  become: false
  # there were situations were the core-lib stayed old

- name: Get full path of repository
  ansible.builtin.command: "realpath {{ role_path }}/../../.."
  delegate_to: localhost
  register: repo_dir
  become: false
  changed_when: false

- name: Synchronize host shepherd dir to target
  ansible.posix.synchronize:
    src: "{{ repo_dir.stdout }}/software"
    dest: "{{ sheep_install_path }}/software"
    delete: true
    owner: false
    group: false
    compress: false
    rsync_opts:
      - "--exclude=.eggs"
      - "--exclude=__pycache__"
  when: sheep_refresh_source | bool

- name: Own shepherd codebase
  ansible.builtin.file:
    path: "{{ sheep_install_path }}/"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "a+rw"
    recurse: true
  become: true
  tags:
    - source-code
    - python
