---

- name: Add systemd unit
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '/etc/systemd/system/'
    mode: '0644'
  loop:
    - shepherd.service
    - shepherd-rpc.service
    - shepherd-launcher.service
  tags:
    - install
    - systemd

- name: Configure systemd services
  ansible.builtin.systemd:
    name: '{{ item.name }}'
    state: stopped
    enabled: '{{ item.enabled }}'
    daemon_reload: true
  loop:
    - { name: shepherd, enabled: false}
    - { name: shepherd-rpc, enabled: false}
    - { name: shepherd-launcher, enabled: true}
    - { name: systemd-timesyncd, enabled: false}
  tags:
    - conf
    - systemd

# NOTE: could avoid a restart by issuing "sudo systemctl daemon-reload"

- name: Disable connman automatic time update
  ansible.builtin.command:
    cmd: 'busctl --system call net.connman / net.connman.Clock SetProperty sv "TimeUpdates" s "manual"'
  failed_when: false  # services may not exist in newer releases (ubuntu 20.04 ++)
  changed_when: true
  tags:
    - conf
    - systemd
