---

- name: Deploy example configuration
  ansible.builtin.copy:
    src: "{{ sheep_install_path }}/software/python-package/{{ item }}"
    dest: "{{ sheep_config_path }}/"
    force: false
    owner: "{{ ansible_user }}"
    mode: 'a+rw'
    remote_src: true
  loop:
    - example_config_emulation.yaml
    - example_config_harvest.yaml
  tags:
    - source-code
    - python
    - conf

- name: Deploy default configuration for launcher (harvest)
  ansible.builtin.copy:
    src: "{{ sheep_install_path }}/software/python-package/example_config_harvest.yaml"
    dest: "{{ sheep_config_path }}/config.yaml"
    force: false
    owner: "{{ ansible_user }}"
    mode: 'a+rw'
    remote_src: true
  tags:
    - source-code
    - python
    - conf

- name: Symlink to shepherd-sheep for compatibility with deb package (might fail -> already exists)
  ansible.builtin.file:
    src: "/usr/local/bin/shepherd-sheep"
    path: "/usr/bin/shepherd-sheep"
    state: link
    follow: true
  failed_when: false
  tags:
    - install
    - python

# Last operation in sheep-install -> installer uses it as detector / flag
- name: Make Shepherd Module permanent
  ansible.builtin.lineinfile:
    dest: "/etc/modules"
    regexp: "#?shepherd.*$"
    line: "shepherd"
    state: present

- name: Start in software-dir after login
  ansible.builtin.lineinfile:
    dest: '{{ item }}/.bashrc'
    line: 'cd /opt/shepherd/software'
    regex: "#?cd \/opt\/shepherd.*$"
    insertafter: 'EOF'
    state: present
  loop:
    - '/home/{{ ansible_user }}'
    - '/root'
