---
### detect if already installed -> check last OP of this role
- name: Detect Install-Status (last OP of sheep-role)
  ansible.builtin.lineinfile:
    dest: "/etc/modules"
    regexp: "#?shepherd.*$"
    line: "shepherd"
    state: present
  check_mode: true  # file will not be altered
  register: detector

### Install & Config
- name: APT - Update Cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Configure Shepherd - Pre-Phase
  ansible.builtin.include_tasks:
    file: "{{ file_item }}"
  loop:
    - config_folders.yml
    - config_overlays.yml
  loop_control:
    loop_var: file_item
  when:  # NOTE: all have to be true (AND)
    - sheep_install_basics | bool
    - detector.changed
  tags:
    - install

- name: Install Pre-Requisites
  ansible.builtin.include_tasks:
    file: "{{ file_item }}"
  loop:
    - toolchain_kernel.yml
    - toolchain_py.yml
  loop_control:
    loop_var: file_item
  when:
    - sheep_install_basics | bool
    - detector.changed
  tags:
    - install

- name: Install Ti-Toolchain for PRU
  ansible.builtin.include_tasks:
    file: toolchain_pru_ti.yml
  when:
    - sheep_install_basics | bool
    - sheep_install_ti_tools | bool
    - detector.changed
  tags:
    - install

- name: Install GCC-Toolchain for PRU
  ansible.builtin.include_tasks:
    file: toolchain_pru_gcc.yml
  when:
    - sheep_install_basics | bool
    - sheep_install_gcc_tools | bool
    - detector.changed
  tags:
    - install

- name: Restart device after installing PreReqs (& changing overlays)
  ansible.builtin.reboot:
    connect_timeout: 20
    reboot_timeout: 200
    post_reboot_delay: 30
  when:
    - sheep_install_basics | bool
    - detector.changed

### Build
- name: Build Shepherd-Software
  ansible.builtin.include_tasks:
    file: "{{ file_item }}"
  loop:
    - build_pre.yml
    - build_shp.yml
    - build_post.yml
  loop_control:
    loop_var: file_item
  tags:
    - install
    - build

### Config
- name: Configure Shepherd - Post-Phase
  ansible.builtin.include_tasks:
    file: "{{ file_item }}"
  loop:
    - config_systemd.yml
    - config_shepherd.yml
  loop_control:
    loop_var: file_item
  when:
    - sheep_install_basics | bool
    - detector.changed
  tags:
    - install

- name: Restart device after setup (specially services)
  ansible.builtin.reboot:
    connect_timeout: 20
    reboot_timeout: 200
    post_reboot_delay: 30
  when:
    - sheep_install_basics | bool
    - detector.changed
