---

- name: Get kernel version
  ansible.builtin.command: 'uname --kernel-release'
  register: kernelrelease
  changed_when: false

- name: APT - Install required packages for kernel compilation
  ansible.builtin.apt:
    name:
      [
        "linux-headers-{{ kernelrelease.stdout.strip() }}", # redundancy, 1st done by maintenance
        # "dkms", # TODO: test removal - should not be needed - installs huge secondary gcc
        "bb-cape-overlays",  # not a part of ubuntu 22.4, also missing from default repo (readd ee/focal)
      ]
    state: present
    update_cache: true
