---

- name: APT - Install required packages for Python
  ansible.builtin.apt:
    name:
      [
        "zlib1g-dev",
        "libjpeg-dev",
        "hdf5-tools", # h5py
        "libhdf5-dev", # h5py
        "libopenblas*", # numpy
        "libdbus-glib-1-dev",
        "libgirepository1.0-dev",
        "srecord",
        "cmake", # for custom build
        "build-essential", # for custom build
        "python3-dev", # for custom build
      ]
    state: present

- name: PIP - Install | upgrade UV
  # Note: done via pip to get universal access (root, sudo, jane)
  ansible.builtin.command:
    cmd: pip install uv --upgrade --break-system-packages
  become: true

- name: Allow install to tool-dir without sudo
  ansible.builtin.file:
    path: "/usr/local/bin/"
    state: directory
    mode: 'a+rwx' # everyone can list and access files inside
  become: true
