---

- name: APT - Install required packages for Python
  ansible.builtin.apt:
    name:
      [
        "ntpdate", # allows manual time updates via ntpdate -s time.nist.gov
        "zlib1g-dev",
        "libjpeg-dev",
        "hdf5-tools", # h5py
        "libhdf5-dev", # h5py
        "libopenblas*", # numpy
        "libdbus-glib-1-dev",
        "libgirepository1.0-dev",
        "srecord",
      ]
    state: present

- name: UV - install
  ansible.builtin.command:
    cmd: 'curl -LsSf https://astral.sh/uv/install.sh | sh'
    chdir: '/home/{{ ansible_user }}'
  become: false
  # this should add to .bashrc: . "$HOME/.local/bin/env"

- name: UV - create venv
  ansible.builtin.command:
    cmd: 'uv venv'
    chdir: '/home/{{ ansible_user }}'

- name: UV - activate venv on login
  ansible:builtin:lineinfile:
    dest: '{{ item[1] }}/.bashrc'
    line: ". '/home/{{ ansible_user }}/.venv/bin/activate'"
    regex: "#?\. [\"'].*venv\/bin\/activate[\"'].*$"
    insertafter: 'EOF'
    state: present
  loop:
    - '/home/{{ ansible_user }}'
    - '/root'
  become: true

- name: UV - compile & install python-packages
  # NOTE: with the added index a compilation can be avoided
  # only possible up to debian bookworm / py 3.11 ATM
  ansible.builtin.command:
    cmd: 'uv pip install {{ item }} --index=https://www.piwheels.org/simple'
    chdir: '/home/{{ ansible_user }}'
  loop:
    - numpy  # 110 min
    - h5py  # 54 min, needs numpy
    - gevent  # 35 min
    - zstandard  # 21 min
    - pyzmq  # 25 min

- name: UV - install more python-packages (< 1min/item)
  ansible.builtin.command:
    cmd: 'uv pip install {{ item }}'
    chdir: '/home/{{ ansible_user }}'
  loop:
    - psutil
    - msgpack
    - pydantic
    - click
    - shepherd-core
