---

- name: APT - Install required packages for Python
  ansible.builtin.apt:
    name:
      [
        "ntpdate", # allows manual time updates via ntpdate -s time.nist.gov
        "zlib1g-dev",
        "libjpeg-dev",
        "python3-numpy",
        "python3-zmq",
        "python3-gevent",
        "python3-h5py",
        "python3-pip",
        "python3-setuptools",
        "python3-virtualenv",
        "python3-msgpack",
        "libdbus-glib-1-dev",
        "libgirepository1.0-dev",
        # pip on ubuntu 22.04 began to compile (forever) ... so use apt instead:
        "python3-pytest",
        "python3-pytest-click",
        "python3-pytest-timeout",
        "python3-pyfakefs",
        "python3-coverage",
        # normal shepherd-package
        "python3-click",
        "python3-psutil",
        # shepherd-core - database-support
        "python3-zstd",
        # "python3-sqlalchemy",  # TODO: temporary
        "srecord",
      ]
    state: present

- name: PIP - update essential base-packages (setuptools, pip, ...)
  ansible.builtin.pip:
    name:
      [
        "pip",
        "setuptools",
        "wheel",
        "virtualenv",
      ]
    extra_args: --upgrade --break-system-packages # debian locks root env
  when: true
  # NOTE: not the cleanest solution - packages managed by apt but setup for pyPackage failed recently
  # TODO: switch all pip-additions to virtual env?
