#ifndef __PROG_SBW_JTAG_H_
#define __PROG_SBW_JTAG_H_

#include <stdint.h>

#define SBW_SUCCESS                (0u)
#define SBW_ERR_GENERIC            (1u)
#define SBW_ERR_ET_DCDC_IDCODE     (2u)
#define SBW_ERR_ET_DCDC_DEVID      (3u)
#define SBW_ERR_ET_DCDC_CPU_STATE  (4u)
#define SBW_ERR_ET_DCDC_FLASH_VERI (5u)
#define STATUS_FUSEBLOWN           (6u)
#define STATUS_ACTIVE              (7u)
#define STATUS_IDLE                (8u)

// Constants for data formats, dedicated addresses
#define F_BYTE                     (8u)
#define F_WORD                     (16u)
#define F_ADDR                     (20u)
#define F_LONG                     (32u)
#define V_RESET                    (0xFFFEu)
#define V_BOR                      (0x1B08u)

#define RSTLOW_SBW                 (0u)
#define RSTLOW_JTAG                (1u)
#define RSTHIGH_SBW                (2u)
#define RSTHIGH_JTAG               (3u)

// Set the JTAG control signal register
#define IR_CNTRL_SIG_16BIT         (0xC8u) // original value: 0x13
// Read out the JTAG control signal register
#define IR_CNTRL_SIG_CAPTURE       (0x28u) // original value: 0x14
// Release the CPU from JTAG control
#define IR_CNTRL_SIG_RELEASE       (0xA8u) // original value: 0x15

// Instructions for the JTAG fuse
// Prepare for JTAG fuse blow
#define IR_PREPARE_BLOW            (0x44u) // original value: 0x22
// Perform JTAG fuse blow
#define IR_EX_BLOW                 (0x24u) // original value: 0x24

// Instructions for the JTAG data register
// Set the MSP430 MDB to a specific 16-bit value with the next
// 16-bit data access
#define IR_DATA_16BIT              (0x82u) // original value: 0x41
// Set the MSP430 MDB to a specific 16-bit value (RAM only)
#define IR_DATA_QUICK              (0xC2u) // original value: 0x43

// Instructions for the JTAG PSA mode
// Switch JTAG data register to PSA mode
#define IR_DATA_PSA                (0x22u) // original value: 0x44
// Shift out the PSA pattern generated by IR_DATA_PSA
#define IR_SHIFT_OUT_PSA           (0x62u) // original value: 0x46

// Instructions for the JTAG address register
// set the MSP430 MAB to a specific 16-bit value
// Use the 20-bit macro for 430X and 430Xv2 architectures
#define IR_ADDR_16BIT              (0xC1u) // original value: 0x83
// Read out the MAB data on the next 16/20-bit data access
#define IR_ADDR_CAPTURE            (0x21u) // original value: 0x84
// Set the MSP430 MDB with a specific 16-bit value and write
// it to the memory address which is currently on the MAB
#define IR_DATA_TO_ADDR            (0xA1u) // original value: 0x85
// Bypass instruction - TDI input is shifted to TDO as an output
#define IR_BYPASS                  (0xFFu) // original value: 0xFF
#define IR_DATA_CAPTURE            (0x42u)

// JTAG identification values for all existing Flash-based MSP430 devices
// JTAG identification value for 430X architecture devices
#define JTAG_ID                    (0x89u)
// JTAG identification value for 430Xv2 architecture devices
#define JTAG_ID91                  (0x91u)
// JTAG identification value for 430Xv2 architecture FR4XX/FR2xx devices
#define JTAG_ID98                  (0x98u)
// JTAG identification value for 430Xv2 architecture FR59XX devices
#define JTAG_ID99                  (0x99u)
// Additional instructions for JTAG_ID91 architectures
// Instruction to determine device's CoreIP
#define IR_COREIP_ID               (0xE8u) // original value: 0x17
// Instruction to determine device's DeviceID
#define IR_DEVICE_ID               (0xE1u) // original value: 0x87

// Request a JTAG mailbox exchange
#define IR_JMB_EXCHANGE            (0x86u) // original value: 0x61
// Instruction for test register in 5xx
#define IR_TEST_REG                (0x54u) // original value: 0x2A
// Instruction for 3 volt test register in 5xx
#define IR_TEST_3V_REG             (0xF4u) // original value: 0x2F

// JTAG mailbox constant -
#define OUT1RDY                    (0x0008u)
// JTAG mailbox constant -
#define IN0RDY                     (0x0001u)
// JTAG mailbox constant -
#define JMB32B                     (0x0010u)
// JTAG mailbox constant -
#define OUTREQ                     (0x0004u)
// JTAG mailbox constant -
#define INREQ                      (0x0001u)
// JTAG mailbox mode 32 bit -
#define MAIL_BOX_32BIT             (0x10u)
// JTAG mailbox moede 16 bit -
#define MAIL_BOX_16BIT             (0x00u)

#define ERASE_MAIN                 (0xA506u) // erase of the entire flash main memory
#define ERASE_BANK                 (0xA504u) // erase of a single flash memory bank
#define ERASE_SEGMENT              (0xA502u) // erase of the selected flash memory segment
#define MAIN_ERASE                 (0x1A1Au) // erase of the FRAM Main memory on FR5xx/FR6xx
#define TOTAL_ERASE (0x1B1Bu) // erase of the FRAM Main, INFO  & IP protected memory on FR5xx/FR6xx
/* Erase of the FRAM Main & INFO memory including JTAG lock signature on FR4xx */
#define USER_CODE_ERASE (0x1A1Au)
#define STOP_DEVICE     (0xA55Au)

/**
 * Reads a 32bit value from the JTAG mailbox.
 *
 * @returns 32bit value from JTAG mailbox
 */
int      sbw_jtag_read_jmb_out(void);

/**
 * Writes a 16bit value into the JTAG mailbox system. The function timeouts if the mailbox is not
 * empty after a certain number of retries.
 *
 * @param data data to be shifted into mailbox
 */
int      sbw_jtag_write_jmb_in16(uint16_t data);

/**
 * Writes a 32bit value into the JTAG mailbox system. The function timeouts if the mailbox
 * is not empty after a certain number of retries.
 *
 * @param dataX data to be shifted into mailbox
 * @param dataY data to be shifted into mailbox
 *
 */
int      sbw_jtag_write_jmb_in32(uint16_t dataX, uint16_t dataY);

/* Loads a JTAG instruction into the JTAG instruction register (IR) of the target device */
uint32_t tap_ir_shift(uint8_t instruction);

/* Loads a 16-bit word into the JTAG data register */
uint16_t tap_dr_shift16(uint16_t data);

/* Loads a 20-bit word into the JTAG data register */
uint32_t tap_dr_shift20(uint32_t address);

/* Connect the JTAG/SBW Signals and execute delay */
int      sbw_jtag_connect(void);

/* Stop JTAG/SBW by disabling the pins and executing delay */
int      sbw_jtag_disconnect(void);

/**
 * Applies the sequence to enter SBW mode with reset pin set high. Device starts
 * executing code.
 */
void     sbw_entry_sequence();
/* Applies the sequence to enter SBW mode with reset pin set low. Device halts. */
void     sbw_entry_sequence_rst_low();

/* Resets the TAP controller state machine */
void     tap_reset(void);

/**
 * Enables JTAG communication with a target. Use JSBW mode if device is in LPM5 mode.
 *
 * @returns JTAG_ID91(0x91) if connection was established successfully, invalid JTAG ID (0x1) otherwise)
 */
uint16_t magicPattern(void);


/**
 * Resync the JTAG connection
 *
 * @returns SBW_SUCCESS if operation was successful, SBW_ERR_GENERIC otherwise
 *
 * @see SLAU320AJ 2.3.2.2.1
 */
int      sbw_jtag_sync(void);

#endif /* __PROG_SBW_JTAG_H_ */
