---

# user can control rule by altering these vars from outside
maintenance_timezone: Europe/Berlin
maintenance_kernel_pin: "4.19.280-bone76" # TODO: trial
  # 4.19.94-ti-r74"  # 2025-06-23: r74 was newest
