---

# user can control rule by altering these vars from outside
maintenance_update_kernel: false
maintenance_update_bootloader: false
maintenance_delete_unused_files: true

# rule config
maintenance_default_kernel: lts-4_19
maintenance_kernel_pin: "4.19.94-ti-r74"  # 2024-07-03: r74 was newest
# -rt -> used for more reliable ptp & gpio-triggering, BUT communication with PRU fails
maintenance_timezone: Europe/Berlin
