---

# user can control rule by altering these vars from outside
maintenance_timezone: Europe/Berlin
maintenance_kernel_pin: "6.1.83-ti-r42" # TODO: trial
# 6.1.83-ti-r42
# 6.12.34-ti-arm32-r12
# 6.18.42-bone46
