name: Test Sheep

on:
  workflow_call:

permissions: {}

jobs:
  sheep-test:
    concurrency:
      group: sheep-${{ github.workflow }}-${{ github.ref }}-${{ matrix.python-version }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.14", "3.13", "3.12", "3.11"]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6
      - name: Install uv 🔧 & set up Python 🐍
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          activate-environment: true
      - name: Install dependencies 🔧
        run: |
          sudo apt update
          sudo apt install python3-msgpack
          uv pip install msgpack -U

      - name: Install the shepherd py-package 🐑
        run: "uv pip install .[test]"
        working-directory: "./software/python-package"
      - name: Test the shepherd py-package (limited test-range) 🐐
        run: "pytest"
        working-directory: "./software/python-package"
        # needs sudo because it installs packages
