name: QA-Test

on:
  push:
    branches: [ "main", "dev" ]
  workflow_call:

jobs:
  static-analysis:
    uses: ./.github/workflows/static_analysis.yaml
  compile-firmwares:
    uses: ./.github/workflows/fw_build_gcc.yaml
  test-sheep:
    uses: ./.github/workflows/py_sheep_test.yaml
  test-herd:
    uses: ./.github/workflows/py_herd_test.yaml

  QA-tests:
    runs-on: ubuntu-latest
    needs:
      - static-analysis
      - compile-firmwares
      - test-sheep
      - test-herd
    steps:
      - name: Finished
        run: echo "finished"
