name: Release tagged Commit

on:
  workflow_call:
  push:
    # branches: [ main ]  # this is handled as OR (push to main OR tagged)
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  QA-tests:
    uses: ./.github/workflows/quality_assurance.yaml

  release:
    runs-on: ubuntu-latest
    needs:
      - QA-tests
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Release 🏃
        uses: softprops/action-gh-release@v2
