name: Generate Docs
# for Github-Pages

on:
  push:
    branches: [ "main" ]
  workflow_call:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-quality-control:
    uses: ./.github/workflows/qc_tests.yml
  build-pages:
    runs-on: ubuntu-latest
    needs:
      - run-quality-control
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Init Submodules (for grabbing readmes) 🔧
        run: git submodule update --init --recursive
      - name: Build and Push Pages 🧱
        uses: sphinx-notes/pages@v3
        with:
          pyproject_extras: ""
          # currently needed because action begins to analyze root pyproject.toml
