name: Generate Docs
# for Github-Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

jobs:
  run-quality-assurance:
    uses: ./.github/workflows/qa_test.yml
  build-pages:
    runs-on: ubuntu-latest
#    needs:
#  - run-quality-assurance
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:

      - name: Build and Push Pages 🧱
        uses: sphinx-notes/pages@v3
